# Pre-commit hooks for code quality
# Run manually: pre-commit run --all-files
# Install: pre-commit install

repos:
  # Python hooks
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix, --unsafe-fixes]
        files: ^backend/

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: ^backend/

  # Temporarily disabled due to SQLAlchemy 2.0 type compatibility issues
  # Will re-enable after upgrading type stubs
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.10.0
  #   hooks:
  #     - id: mypy
  #       files: ^backend/
  #       args: [--ignore-missing-imports]
  #       additional_dependencies:
  #         - types-requests
  #         - sqlalchemy-stubs

  # JavaScript/TypeScript hooks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.3.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        exclude: ^frontend/dist/
        additional_dependencies:
          - eslint@8.57.0
          - '@typescript-eslint/parser@6.21.0'
          - '@typescript-eslint/eslint-plugin@6.21.0'
          - 'eslint-plugin-react@7.34.1'
          - 'eslint-plugin-react-hooks@4.6.0'
          - 'eslint-plugin-react-refresh@0.4.6'

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|json|css|md)$
        exclude: ^(frontend/dist/|backend/)

  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-json
      - id: check-merge-conflict
      - id: detect-private-key
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Security checks - disabled for now as it requires proper baseline setup
  # - repo: https://github.com/Yelp/detect-secrets
  #   rev: v1.5.0
  #   hooks:
  #     - id: detect-secrets
  #       args: ['--baseline', '.secrets.baseline']
  #       exclude: package-lock\.json

# Configuration
default_language_version:
  python: python3.9
  node: 20.11.0

fail_fast: false
